<?php

return [
    ['name' => 'Scheduling', 'description' => 'Organizing and setting time frames for tasks and events.'],
    ['name' => 'Communication', 'description' => 'Effectively conveying information and ideas.'],
    ['name' => 'Organization', 'description' => 'Arranging resources and tasks in a systematic manner.'],
    ['name' => 'Attention to Detail', 'description' => 'Focusing on small aspects and ensuring nothing is overlooked.'],
    ['name' => 'Delegation', 'description' => 'Assigning tasks and responsibilities to others.'],
    ['name' => 'Leadership', 'description' => 'Guiding and motivating a team to achieve goals.'],
    ['name' => 'Documentation', 'description' => 'Creating, maintaining, and organizing written records and materials.'],
    ['name' => 'Oversight', 'description' => 'Monitoring tasks, processes, or teams to ensure success and compliance.'],
    ['name' => 'Time Management', 'description' => 'Prioritizing tasks and managing time effectively.'],
    ['name' => 'Reporting', 'description' => 'Providing regular updates and analyses on activities and outcomes.'],
    ['name' => 'Planning', 'description' => 'Strategizing and organizing tasks, goals, and resources.'],
    ['name' => 'Organizational Skills', 'description' => 'Ability to arrange tasks and resources efficiently.'],
    ['name' => 'Adaptability', 'description' => 'Adjusting to changing circumstances and challenges.'],
    ['name' => 'Problem-Solving', 'description' => 'Identifying issues and finding effective solutions.'],
    ['name' => 'Coordination', 'description' => 'Ensuring different elements work together effectively.'],
    ['name' => 'Crisis Management', 'description' => 'Managing unexpected events or emergencies.'],
    ['name' => 'Multitasking', 'description' => 'Handling multiple tasks simultaneously with focus and effectiveness.'],
    ['name' => 'Menu Planning', 'description' => 'Designing meal options or event menus.'],
    ['name' => 'Culinary Knowledge', 'description' => 'Understanding ingredients, cooking techniques, and food safety.'],
    ['name' => 'Creativity', 'description' => 'Thinking outside the box and coming up with innovative ideas.'],
    ['name' => 'Quality Assessment', 'description' => 'Evaluating products or services to ensure they meet standards.'],
    ['name' => 'Sensory Evaluation', 'description' => 'Assessing qualities like taste, smell, texture, and appearance.'],
    ['name' => 'Logistics', 'description' => 'Managing the movement of goods, services, and information.'],
    ['name' => 'Space Planning', 'description' => 'Designing efficient layouts for spaces and resources.'],
    ['name' => 'Design Sense', 'description' => 'Aesthetic awareness and ability to create appealing designs.'],
    ['name' => 'Flexibility', 'description' => 'Being open to changes and new ideas.'],
    ['name' => 'Guest Focus', 'description' => 'Prioritizing guest satisfaction and experience.'],
    ['name' => 'Budgeting', 'description' => 'Creating and managing financial plans and expenditures.'],
    ['name' => 'Customer Service', 'description' => 'Assisting and meeting the needs of customers effectively.'],
    ['name' => 'Interior Design', 'description' => 'Creating aesthetically pleasing and functional indoor spaces.'],
    ['name' => 'Professionalism', 'description' => 'Exhibiting expertise, behavior, and a positive attitude in work.'],
    ['name' => 'Listening Skills', 'description' => 'Paying attention to and understanding what others are saying.'],
    ['name' => 'Artistic Skills', 'description' => 'Creating visual art or performing arts with skill and creativity.'],
    ['name' => 'Advanced Makeup Techniques', 'description' => 'Applying makeup with high-level techniques for various purposes.'],
    ['name' => 'Precision', 'description' => 'Performing tasks with exactness and accuracy.'],
    ['name' => 'Basic Makeup Skills', 'description' => 'Applying makeup with fundamental techniques and knowledge.'],
    ['name' => 'Grooming Knowledge', 'description' => 'Understanding grooming practices for personal care.'],
    ['name' => 'Versatility', 'description' => 'Ability to adapt to a variety of tasks and environments.'],
    ['name' => 'Quick Setup', 'description' => 'Setting up equipment or tasks in an efficient and fast manner.'],
    ['name' => 'Storytelling', 'description' => 'Conveying narratives in an engaging and creative manner.'],
    ['name' => 'Photography', 'description' => 'Capturing images using cameras and other photographic equipment.'],
    ['name' => 'Aesthetic Sense', 'description' => 'Having an eye for beauty and design in various forms.'],
    ['name' => 'Technical Skills', 'description' => 'Proficiency in using tools, technology, or technical systems.'],
    ['name' => 'Drone Operation', 'description' => 'Controlling drones for various tasks, including aerial photography.'],
    ['name' => 'AV Skills', 'description' => 'Operating and troubleshooting audio-visual equipment.'],
    ['name' => 'Technical Setup', 'description' => 'Arranging technical equipment for events or tasks.'],
    ['name' => 'Video Editing', 'description' => 'Editing video content for quality and presentation.'],
    ['name' => 'Photo Editing', 'description' => 'Enhancing and modifying photos for better visual appeal.'],
    ['name' => 'Efficiency', 'description' => 'Completing tasks in the least amount of time and resources.'],
    ['name' => 'Data Handling', 'description' => 'Managing, storing, and processing data effectively.'],
    ['name' => 'Design Knowledge', 'description' => 'Understanding design principles and aesthetics.'],
    ['name' => 'Graphic Design', 'description' => 'Creating visual content using design software and artistic principles.'],
    ['name' => 'Typography', 'description' => 'Working with fonts and text layout to create readable, attractive designs.'],
    ['name' => 'Spatial Design', 'description' => 'Designing spaces and layouts with attention to functionality and aesthetics.'],
    ['name' => 'Project Coordination', 'description' => 'Organizing tasks and people to achieve a project’s objectives.'],
    ['name' => 'Floral Arrangement', 'description' => 'Designing and arranging flowers for various occasions.'],
    ['name' => 'Gardening', 'description' => 'Cultivating and maintaining plants in gardens or landscapes.'],
    ['name' => 'Project Planning', 'description' => 'Creating a structured approach for achieving project goals.'],
    ['name' => 'Finishing Skills', 'description' => 'Applying final touches to a product or project for completion.'],
    ['name' => 'Event Planning', 'description' => 'Coordinating all aspects of events from start to finish.'],
    ['name' => 'Audio-Visual Knowledge', 'description' => 'Understanding and using audio-visual equipment and technology.'],
    ['name' => 'Music Knowledge', 'description' => 'Understanding music theory, genres, and performance techniques.'],
    ['name' => 'Event Management', 'description' => 'Overseeing the organization and execution of events.'],
    ['name' => 'Event Coordination', 'description' => 'Handling the logistics and details of an event for smooth execution.'],
];
